# Generated by Django 2.2.3 on 2019-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.BigIntegerField(),
        ),
    ]
